# Generated by Django 3.0 on 2019-12-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('goal_difference', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capital', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soccerplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('goals', models.PositiveIntegerField()),
                ('injured', models.BooleanField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('DMF', 'Definsive_midfielder'), ('OMF', 'Offensive_midfielder'), ('STR', 'Striker')], max_length=3, null=True)),
                ('birth', models.DateField()),
                ('clubs', models.ManyToManyField(blank=True, to='soccer.Club')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.Country')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(blank=True, to='soccer.Soccerplayer'),
        ),
    ]
