# Generated by Django 3.0 on 2019-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='players',
        ),
        migrations.AlterField(
            model_name='soccerplayer',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='players', to='soccer.Club'),
        ),
    ]
