# Generated by Django 3.0 on 2019-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_auto_20191218_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerplayer',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='soccerplayers', to='soccer.Club'),
        ),
    ]
