# Generated by Django 3.0 on 2019-12-21 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20191218_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='founded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soccerplayer',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='soccerplayer', to='soccer.Club'),
        ),
    ]
